baseURL = "http://vjeantet.fr/"
languageCode = "fr-FR"
defaultContentLanguage = "fr"
title = "Valère JEANTET"
theme = "github-style"
copyright = "All rights reserved"
pygmentsCodeFences = true
pygmentsUseClasses = true
pluralizelisttitles = false

[pagination]
pagerSize = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
author = "Valère JEANTET"
description = "IT software and Security Engineer, Open source enthusiast."
keywords = "blog, security, golang, hugo, devops"
github = "vjeantet"
twitter = "vjeantet"
email = "valere.jeantet@gmail.com"
url = "http://vjeantet.fr"
avatar = "/images/logo.png"
headerIcon = "/images/github-mark-white.png"
favicon = "/images/logo.png"
location = "Paris, France"
rss = true
lastmod = true
enableSearch = true
defer_custom_js = ["/js/netlify-identity.js"]

[[params.links]]
title = "Mastodon"
href = "https://hachyderm.io/@vjeantet"
icon = "/images/mastodon.png"

[[params.links]]
title = "Keybase (secure msg)"
href = "https://keybase.io/vjeantet"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
tag = "tags"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[permalinks]
post = "/:slug/"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
