baseurl = "http://vjeantet.fr/"
copyright = "All rights reserved"
locale = "fr-FR"
defaultContentLanguage = "fr"
pluralizelisttitles = false
theme = "hugo-paper"
title = "Valère JEANTET"
enableInlineShortcodes = true

[pagination]
pagerSize = 5

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[[menu.main]]
name = "About"
url = "/about/"
weight = 10

[params]
env = "production"
author = "Valère JEANTET"
name = "Valère JEANTET"
bio = "IT software and Security Engineer, Open source enthusiast."
description = "Whatever the mind of man can conceive and believe, it can achieve."
avatar = "https://vjeantet.fr/images/logo.png"
color = "light"
mainSections = ["post"]
github = "vjeantet"
twitter = "vjeantet"
mastodon = "https://hachyderm.io/@vjeantet"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[permalinks]
post = "/:slug/"

[services]
[services.disqus]
shortname = "vjeantet"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
