baseURL = "http://vjeantet.fr/"
languageCode = "fr-FR"
defaultContentLanguage = "fr"
title = "Valère JEANTET"
theme = "archie"
copyright = "All rights reserved"
pygmentsstyle = "monokai"
pygmentsCodeFences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true
pluralizelisttitles = false

[pagination]
pagerSize = 10

[outputs]
home = ["HTML", "RSS"]

[params]
mode = "auto"
useCDN = false
author = "Valère JEANTET"
subtitle = "IT software and Security Engineer, Open source enthusiast."
description = "IT software and Security Engineer, Open source enthusiast."
keywords = "blog, security, golang, hugo, devops"
favicon = "/images/logo.png"
mainSections = ["post"]
defer_custom_js = ["/js/netlify-identity.js"]
customJS = ["js/daily-color.js"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/vjeantet"

[[params.social]]
name = "Bluesky"
icon = "simple:bluesky"
url = "https://bsky.app/profile/vjeantet.bsky.social"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/valerejeantet"

[[params.social]]
name = "Signal (secure msg)"
icon = "simple:signal"
url = "https://signal.me/#eu/8vo6HxU6m15mccSy0_302yOQPGylFau5F0euYupiRNM45-d6xUhC7oKs1F0g4IzV"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 5

[security]
allowContent = ['^text/']

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
tag = "tags"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[permalinks]
post = "/:slug/"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
